---
title: "Map generator"
---
This file generates the png's used in the weather map.

There are some big outliers that reduce the precision of the colors. Floor/ceiling points that are outside [.025, .975].




## Plot generator fn
```{r, message=F}
library(maptools); library(sp); library(gstat); library(ggplot2); library(png); library(readr); library(tidyverse)

states <- readShapePoly("data/statesp020.shp")
```

Generate Single Map for red

```{r}
generate1Map <- function(df){
  # min/max coords of the interpolation area
  x.range <- as.numeric(c(-127, -65))
  y.range <- as.numeric(c(23, 51))
  
  grd <- expand.grid(x = seq(from = x.range[1], to = x.range[2], by = 0.1), y = seq(from = y.range[1], 
      to = y.range[2], by = 0.1))  # creates grid of points, according to grid extent
  coordinates(grd) <- ~x + y
  gridded(grd) <- TRUE #promotes non-gridded structure to gridded
  
  # Here dataset is read
  ds_coords <- df
  coordinates(ds_coords) <- ~long + lat
  
  # Calculate interpolation
  idw <- idw(formula = re ~ 1, locations = ds_coords, 
    newdata = grd)

  idw.output <- as.data.frame(idw)
  names(idw.output)[1:3] <- c("long", "lat", "var1.pred")
  
  idw.output <- idw.output[ , -4]
  
  m <- ggplot() + 
  geom_tile(data = idw.output, alpha = 0.8, aes(x = long, y = lat, 
    fill = round(var1.pred, 0))) + 
  coord_cartesian(xlim = c(-127, -65), ylim = c(23, 51)) +
  scale_fill_gradientn(colors = c("#FFFFFF","#FFFFFF","#FFFFFF", "#fff7ec", "#fee8c8", "#fdd49e", "#fdbb84", "#fc8d59", "#ef6548",
                                  "#d7301f", "#b30000", "#7f0000"), limits = c(0,30)) + 
  geom_path(data = states, aes(long, lat, group = group), colour = "grey") +
  geom_point(data = df, aes(x = long, y = lat), shape = 21, 
        colour = "red") + 
  geom_text(data = df, aes(label=city, x = long, y = lat), 
            size=3, nudge_x = 3, nudge_y = .1) +
  labs(fill = "Mean Absolute Rain Error") +
  theme(legend.position = c(.4, .02), #(x,y)
        legend.direction = "horizontal",
        legend.text = element_text(size=14),
        legend.title = element_text(size=17),
        plot.margin=grid::unit(c(-3,-8.5, 6,-8.8), "mm"),
        axis.line=element_blank(),
        axis.text.x=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks=element_blank(),
        axis.title.x=element_blank(),
        axis.title.y=element_blank(),
        panel.background=element_blank(),
        panel.border=element_blank(),
        panel.grid.major=element_blank(),
        panel.grid.minor=element_blank(),
        plot.background=element_blank())
  
  writeLines("Saving in pics folder...")
  ggsave(filename = paste("red map 7.png", sep = ""), plot = m,
    width = 18, height = 12, 
     units = "cm", 
     dpi = 300,
    path = "pics")
  writeLines("Finished")
}
```

```{r}
# This dataset is precip_acc_city3, which is same as precip_acc_city2 but with long lat. It is cp0.01
re_city <- read.csv("data/re_city.csv")

# Delete the following line to include all city names
re_city$city[!re_city$city %in% c("Springfield",
"Portland",
"Hoquiam",
"Charleston",
"Sault Ste Marie",
"Duluth",
"Eugene",
"Miami",
"Montpelier",
"North Platte"
)] <- NA

generate1Map(re_city)
```

For 0.07 red map

```{r}
# This dataset is precip_acc_city3, which is same as precip_acc_city2 but with long lat. It is cp0.01
re_city <- read.csv("data/precip_acc_city7.csv")

# Delete the following line to include all city names
re_city$city[!re_city$city %in% c("Springfield",
"Portland",
"Hoquiam",
"Charleston",
"Sault Ste Marie",
"Duluth",
"Eugene",
"Miami",
"Montpelier",
"North Platte"
)] <- NA

# Change file name in function definition.
generate1Map(re_city)
```




Generate Single Map for blue

```{r}
generate1Map <- function(df, map_name="some map"){
  # min/max coords of the interpolation area
  x.range <- as.numeric(c(-127, -65))
  y.range <- as.numeric(c(23, 51))
  
  grd <- expand.grid(x = seq(from = x.range[1], to = x.range[2], by = 0.1), y = seq(from = y.range[1], 
      to = y.range[2], by = 0.1))  # creates grid of points, according to grid extent
  coordinates(grd) <- ~x + y
  gridded(grd) <- TRUE #promotes non-gridded structure to gridded
  
  # Here dataset is read
  ds_coords <- df
  coordinates(ds_coords) <- ~long + lat
  
  # Calculate interpolation
  idw <- idw(formula = re ~ 1, locations = ds_coords, 
    newdata = grd)

  idw.output <- as.data.frame(idw)
  names(idw.output)[1:3] <- c("long", "lat", "var1.pred")
  
  idw.output <- idw.output[ , -4]
  
  m <- ggplot() + 
  geom_tile(data = idw.output, alpha = 0.8, aes(x = long, y = lat, 
    fill = round(var1.pred, 0))) + 
  coord_cartesian(xlim = c(-127, -65), ylim = c(23, 51)) +
  scale_fill_gradientn(colors = c("white","white", "#92c5de", "#0571b0", "#034063"),
                       limits = c(-5,30)) + 
  geom_path(data = states, aes(long, lat, group = group), colour = "grey") +
  geom_point(data = df, aes(x = long, y = lat), shape = 21, 
        colour = "red") + 
  geom_text(data = df, aes(label=city, x = long, y = lat), 
            size=1.6, nudge_x = 1.9, nudge_y = .1) +
  labs(fill = "Rain Error") +
  theme(legend.position = c(.4, .02), #(x,y)
        legend.direction = "horizontal",
        legend.text = element_text(size=9),
        legend.title = element_text(size=17),
        plot.margin=grid::unit(c(-3,-8.5, 6,-8.8), "mm"),
        axis.line=element_blank(),
        axis.text.x=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks=element_blank(),
        axis.title.x=element_blank(),
        axis.title.y=element_blank(),
        panel.background=element_blank(),
        panel.border=element_blank(),
        panel.grid.major=element_blank(),
        panel.grid.minor=element_blank(),
        plot.background=element_blank())
  
  writeLines("Saving in pics folder...")
  ggsave(filename = paste(map_name, ".png", sep = ""), plot = m,
    width = 18, height = 12, 
     units = "cm", 
     dpi = 300,
    path = "pics")
  writeLines("Finished")
}
```

```{r}
re_city <- read.csv("data/re_city_blue.csv")

#ggplot(re_city) +
#  geom_density(aes(x=re))

generate1Map(re_city, "blue map 2020-04-04")
```


```{}
# Old color gradients
  scale_fill_gradientn(colors = c("#fa5305", "#fc8d59", "#fdcc8a", "white", 
                                  "white", "#92c5de", "#0571b0", "#034063"),
                       limits = c(-30,30)) + 
```




































Testers

## Import data
```{r}
# setwd("C:/Google Drive/CSUEB/data_expo/4")
library(readr); library(tidyverse)
re_city <- read.csv("data/re_city.csv")
```


## Base script for generating a map
### Import
```{r}
library(maptools); library(sp); library(gstat); library(ggplot2)
states <- readShapePoly("data/statesp020.shp")

coordinates(MYC_test) <- ~long + lat
```

### Interpolation
```{r}
# min/max coords of the interpolation area
x.range <- as.numeric(c(-127, -65))   # c(-125, -65.5)
y.range <- as.numeric(c(23, 51))      # c(24.2, 50)

grd <- expand.grid(x = seq(from = x.range[1], to = x.range[2], by = 0.1), y = seq(from = y.range[1], 
    to = y.range[2], by = 0.1))  # creates grid of points, according to grid extent
coordinates(grd) <- ~x + y
gridded(grd) <- TRUE #promotes non-gridded structure to gridded


idw <- idw(formula = MaxTemp_mae ~ 1, locations = MYC_test, 
    newdata = grd)  # apply idw model for the data

idw.output = as.data.frame(idw)  # output is defined as a data table
names(idw.output)[1:3] <- c("long", "lat", "var1.pred")

# Dropped a column that had all null values.
idw.output <- idw.output[ , -4]
```
```{r}
ggplot(data = MYC_nov) +
  geom_point(aes(x = long, y = lat), shape = 21, 
    colour = "red") +
  geom_text(aes(label=city, x = long, y = lat), 
            size=1.6, nudge_x = 2.3, nudge_y = .1)
```

### Make ggplot map
```{r}
m <- ggplot() + 
  geom_tile(data = idw.output, alpha = 0.8, aes(x = long, y = lat, 
    fill = round(var1.pred, 0))) + 
  coord_cartesian(xlim = c(-127, -65), ylim = c(23, 51)) +
  scale_fill_gradientn(colors = c("cyan", "orange"), limits = c(1,11)) +
  theme() + #(top, right, bottom, left)
  geom_path(data = states, aes(long, lat, group = group), colour = "grey") +
  geom_point(data = MYC_nov, aes(x = long, y = lat), shape = 21, 
        colour = "red") +
  #geom_text(data = MYC_nov, aes(label=city, x = long, y = lat), 
  #          size=1.7, nudge_x = 2, nudge_y = .1) +
  labs(fill = "MAE") +
  theme(legend.position = c(.5, .02), #(x,y)
        legend.direction = "horizontal",
        plot.margin=grid::unit(c(-3,-9, 6,-9), "mm"),
        axis.line=element_blank(),
        axis.text.x=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks=element_blank(),
        axis.title.x=element_blank(),
        axis.title.y=element_blank(),
        panel.background=element_blank(),
        panel.border=element_blank(),
        panel.grid.major=element_blank(),
        panel.grid.minor=element_blank(),
        plot.background=element_blank())

m
```

testing ggsave()
```{r}
ggsave(filename = "nov 14.png", plot = m,
      width = 22, height = 12, 
       units = "cm", 
       dpi = 300,
      path = "pics")

ggsave(filename="myPlot.jpg", plot=lastplot(),
       width = 10, height = 5, 
       units = "cm", # other options are "in", "cm", "mm" 
       dpi = 200
       )
```
